export const testData = 
{ 
  "april":
  [
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },    
    {day_code: 3, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 7, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
  ],

  "may":
  [
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 3, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'may'
    },
    {day_code: 7, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'free',
      night_activities: 'yongen-jaya',
      month: 'may'
    },
    {day_code: 1, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 2, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },    
    {day_code: 3, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 4, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: 'Game Start',
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 5, 
      day_weather: 'cloudy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 6, 
      day_weather: 'clear',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
    {day_code: 7, 
      day_weather: 'rainy',
      night_weather: 'cloudy',
      city: null,
      confidant_events: null,
      special_events: null,
      day_activities: 'unavailable',
      night_activities: 'unavailable',
      month: 'april'
    },
  ]

}